spring:
  application:
    name: bau-platform
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bau_platform
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AWS_COGNITO_ISSUER_URI:http://localhost:8080}
          jwk-set-uri: ${AWS_COGNITO_JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}

# AWS Cognito configuration
aws:
  cognito:
    region: ${AWS_REGION:eu-central-1}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID:local-pool}
    client-id: ${AWS_COGNITO_CLIENT_ID:local-client}
    issuer-uri: ${AWS_COGNITO_ISSUER_URI:http://localhost:8080}

# Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.bau: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api/v1/v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
    config-url: /api/v1/v3/api-docs/swagger-config
    url: /api/v1/v3/api-docs
    disable-swagger-default-url: true
    try-it-out-enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json 