# Local development profile
# Run with: --spring.profiles.active=local

spring:
  # Use H2 in-memory database for local development
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Enable H2 console for database inspection
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Disable JPA show-sql in local for cleaner logs
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  
  # Disable OAuth2 resource server auto-configuration for local development
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

# Custom local settings
bau:
  security:
    mock-auth: true
    # Disable authentication for local development
    permit-all: true

# Logging for local development
logging:
  level:
    com.bau: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 