name: Documentation Quality Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'doc/**/*.md'
      - 'api/**/*.md'
      - 'README.md'
      - '.github/workflows/docs-check.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'doc/**/*.md' 
      - 'api/**/*.md'
      - 'README.md'
      - '.github/workflows/docs-check.yml'

jobs:
  docs-quality:
    name: Documentation Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Markdown Lint
      uses: DavidAnson/markdownlint-cli2-action@v20
      continue-on-error: true
      with:
        globs: |
          doc/**/*.md
          api/**/*.md
          README.md
        config: '.markdownlint.json'
    
    - name: Install German Dictionary
      run: |
        npm install -g cspell @cspell/dict-de-de
        cspell link add @cspell/dict-de-de
        
    - name: Spell Check
      uses: streetsidesoftware/cspell-action@v7
      with:
        files: |
          doc/**/*.md
          api/**/*.md
          README.md
        inline: warning
        config: '.github/cspell.json'
        incremental_files_only: true
        treat_flagged_words_as_errors: false
        strict: true
        suggestions: false
        verbose: false
        check_dot_files: explicit
        use_cspell_files: false
          
    - name: Check Links
      uses: lycheeverse/lychee-action@v2
      with:
        args: |
          --verbose
          --no-progress
          --exclude-all-private
          --exclude-loopback
          --exclude-mail
          --exclude='^file://'
          --exclude='localhost'
          --exclude='127.0.0.1'
          --exclude='github.com/.*/(issues|pull)/'
          'doc/**/*.md' 'api/**/*.md' 'README.md'
        fail: true
        
    - name: Documentation Coverage Report
      run: |
        echo "Documentation Quality Report" >> $GITHUB_STEP_SUMMARY
        echo "================================" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Count documentation files
        MD_COUNT=$(find doc api -name "*.md" | wc -l)
        echo "Markdown files: $MD_COUNT" >> $GITHUB_STEP_SUMMARY
        
        # Count code files that might need documentation
        JAVA_COUNT=$(find backend/src -name "*.java" 2>/dev/null | wc -l || echo "0")
        TS_COUNT=$(find frontend/src -name "*.ts" 2>/dev/null | wc -l || echo "0")
        echo "Java files: $JAVA_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "TypeScript files: $TS_COUNT" >> $GITHUB_STEP_SUMMARY
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All documentation quality checks passed!" >> $GITHUB_STEP_SUMMARY 